BTL_ASP/CuaHangRuou/CuaHangRuou/CuaHangRuou/CuaHangRuou/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CuaHangRuou.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

BTL_ASP/CuaHangRuou/CuaHangRuou/CuaHangRuou/CuaHangRuou/Areas/Admin/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CuaHangRuou.Areas.Admin.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: Admin/SanPham
        public ActionResult QuanLySanPham()
        {
            return View();
        }

        public ActionResult CapNhatSanPham()
        {
            return View();
        }
    }
}

BTL_ASP/CuaHangRuou/CuaHangRuou/CuaHangRuou/CuaHangRuou/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CuaHangRuou.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

BTL_ASP/CuaHangRuou/CuaHangRuou/CuaHangRuou/CuaHangRuou/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CuaHangRuou.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: SanPham
        public ActionResult XemSanPhamTheoDanhMuc()
        {
            return View();
        }
        public ActionResult ChiTietSanPham()
        {
            return View();
        }
        public ActionResult GioHang()
        {
            return View();
        }
        public ActionResult DatHang()
        {
            return View();
        }
        public ActionResult TimKiemSanPham()
        {
            return View();
        }
    }
}

BTL_ASP/CuaHangRuou/CuaHangRuou/CuaHangRuou/CuaHangRuou/Controllers/TaiKhoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CuaHangRuou.Controllers
{
    public class TaiKhoanController : Controller
    {
        // GET: TaiKhoan
        public ActionResult DangKy()
        {
            return View();
        }
        public ActionResult DangNhap()
        {
            return View();
        }
        public ActionResult DoiMatKhau()
        {
            return View();
        }
        public ActionResult SuaTaiKhoan()
        {
            return View();
        }
    }
}

BTL_ASP/CuaHangRuou/CuaHangRuou/CuaHangRuou/CuaHangRuou/Areas/Admin/Views/SanPham/CapNhatSanPham.cshtml
@{
    ViewBag.Title = "CapNhatSanPham";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12 grid-margin">
            <div class="d-flex justify-content-between flex-wrap">
                <div class="d-flex align-items-end flex-wrap">
                    <div class="mr-md-3 mr-xl-5">
                        <h2>Xin chào, Admin</h2>
                        <div class="d-flex">
                            <i class="mdi mdi-home text-muted hover-cursor"></i>
                            <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Quản lý sản phẩm&nbsp;&nbsp;/&nbsp;Cập nhật thông tin sản phẩm</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Cập nhật thông tin sản phẩm</h4>
                <form class="form-sample">
                    <p class="card-description">
                        Nhập thông tin cần sửa
                    </p>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Ảnh sản phẩm *</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Thuộc danh mục</label>
                                <div class="col-sm-9">
                                    <select class="form-control">
                                        <option>Danh mục 1</option>
                                        <option>Danh mục 2</option>
                                        <option>Danh mục 3</option>
                                        <option>Danh mục 4</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Mã sản phẩm *</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Tên sản phẩm *</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Số lượng *</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Thương hiệu</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Loại sản phẩm</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Xuất xứ</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Dung tích</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Nồng độ</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                    </div><div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Tuổi rượu</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Bộ sưu tập</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-9">
                            <div class="form-group row">
                                <label class="col-md-2 col-form-label">Mô tả</label>
                                <div class="col-sm-10">
                                    <textarea type="text" rows="5" class="form-control"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="d-flex justify-content-center">
                        <a class="nav-link mr-2" href="@Url.Action("QuanLySanPham", "SanPham")">
                            <span class="menu-title btn btn-outline-danger btn-fw">Quay lại</span>
                        </a>
                        <a class="nav-link ml-2" href="@Url.Action("QuanLySanPham", "SanPham")">
                            <span class="menu-title btn btn-outline-success btn-fw">Cập nhật</span>
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

BTL_ASP/CuaHangRuou/CuaHangRuou/CuaHangRuou/CuaHangRuou/Areas/Admin/Views/SanPham/QuanLySanPham.cshtml
@{
    ViewBag.Title = "QuanLySanPham";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12 grid-margin">
            <div class="d-flex justify-content-between flex-wrap">
                <div class="d-flex align-items-end flex-wrap">
                    <div class="mr-md-3 mr-xl-5">
                        <h2>Xin chào, Admin</h2>
                        <div class="d-flex">
                            <i class="mdi mdi-home text-muted hover-cursor"></i>
                            <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Quản lý sản phẩm&nbsp;&nbsp;</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Danh sách sản phẩm</h4>
                <a class="nav-link " href="them_san_pham.html">
                    <span class="menu-title btn btn-primary">Thêm sản phẩm</span>
                </a>
                <div class="table-responsive pt-3">
                    <table id="recent-purchases-listing" class="table">
                        <thead>
                            <tr>
                                <th>
                                    #
                                </th>
                                <th>
                                    Mã sản phẩm
                                </th>
                                <th>
                                    Tên sản phẩm
                                </th>
                                <th>
                                    Số lượng
                                </th>
                                <th>
                                    Hành động
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    1
                                </td>
                                <td>
                                    20252025
                                </td>
                                <td>
                                    Sản phẩm 1
                                </td>
                                <td>
                                    1000
                                </td>
                                <td>
                                    <div class="d-flex justify-content-center">
                                        <a class="nav-link " href="@Url.Action("CapNhatSanPham", "SanPham")">
                                            <span class="menu-title btn btn-inverse-warning btn-fw pl-3 pr-3 pt-2 pb-2">Cập nhật</span>
                                        </a>
                                        <a class="nav-link " href="chi_tiet_san_pham.html">
                                            <span class="menu-title btn btn-inverse-info btn-fw pl-3 pr-3 pt-2 pb-2">Xem chi tiết</span>
                                        </a>
                                        <a class="nav-link ">
                                            <span class="menu-title btn btn-inverse-danger btn-fw pl-3 pr-3 pt-2 pb-2">Xóa</span>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    2
                                </td>
                                <td>
                                    20252026
                                </td>
                                <td>
                                    Sản phẩm 2
                                </td>
                                <td>
                                    1000
                                </td>
                                <td>
                                    <div class="d-flex justify-content-center">
                                        <a class="nav-link " href="@Url.Action("CapNhatSanPham", "SanPham")">
                                            <span class="menu-title btn btn-inverse-warning btn-fw pl-3 pr-3 pt-2 pb-2">Cập nhật</span>
                                        </a>
                                        <a class="nav-link " href="chi_tiet_san_pham.html">
                                            <span class="menu-title btn btn-inverse-info btn-fw pl-3 pr-3 pt-2 pb-2">Xem chi tiết</span>
                                        </a>
                                        <a class="nav-link ">
                                            <span class="menu-title btn btn-inverse-danger btn-fw pl-3 pr-3 pt-2 pb-2">Xóa</span>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    3
                                </td>
                                <td>
                                    20252027
                                </td>
                                <td>
                                    Sản phẩm 3
                                </td>
                                <td>
                                    1000
                                </td>
                                <td>
                                    <div class="d-flex justify-content-center">
                                        <a class="nav-link " href="@Url.Action("CapNhatSanPham", "SanPham")">
                                            <span class="menu-title btn btn-inverse-warning btn-fw pl-3 pr-3 pt-2 pb-2">Cập nhật</span>
                                        </a>
                                        <a class="nav-link " href="chi_tiet_san_pham.html">
                                            <span class="menu-title btn btn-inverse-info btn-fw pl-3 pr-3 pt-2 pb-2">Xem chi tiết</span>
                                        </a>
                                        <a class="nav-link ">
                                            <span class="menu-title btn btn-inverse-danger btn-fw pl-3 pr-3 pt-2 pb-2">Xóa</span>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

BTL_ASP/CuaHangRuou/CuaHangRuou/CuaHangRuou/CuaHangRuou/Views/TaiKhoan/DangKy.cshtml
@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="sign-up-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6 col-md-6 p-0">
                <div class="sign-up-bg"></div>
            </div>
            <div class="col-lg-6 col-md-6 p-0">
                <div class="sign-up-form">
                    <h3>Đăng ký</h3>
                    <form>
                        <div class="row">

                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Họ tên</label>
                                    <input type="text" class="form-control" placeholder="Họ tên" spellcheck="false"
                                           data-ms-editor="true">
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Địa chỉ</label>
                                    <input type="email" class="form-control" placeholder="Địa chỉ">
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Số điện thoại</label>
                                    <input type="email" class="form-control" placeholder="Số điện thoại">
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Tên đăng nhập</label>
                                    <input type="text" class="form-control" placeholder="Tên đăng nhập"
                                           spellcheck="false" data-ms-editor="true">
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Mật khẩu</label>
                                    <input type="password" class="form-control" placeholder="Mật khẩu">
                                </div>
                            </div>
                            <div class="col-md-6 offset-md-3">
                                <button type="submit" class="btn default-btn">
                                    Đăng ký
                                </button>
                            </div>
                            <div class="col-lg-12">
                                <p>
                                    Bạn đã có tài khoản?
                                    <a href="@Url.Action("DangNhap","TaiKhoan")">Đăng nhập</a>
                                </p>
                            </div>
                            <div class="col-lg-12">
                                <ul class="social-list">
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-linkedin"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

BTL_ASP/CuaHangRuou/CuaHangRuou/CuaHangRuou/CuaHangRuou/Views/TaiKhoan/DangNhap.cshtml
@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="login-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6 col-md-6 p-0">
                <div class="log-in-bg"></div>
            </div>
            <div class="col-lg-6 col-md-6 p-0">
                <div class="login-form">
                    <h3>Đăng nhập</h3>
                    <form>
                        <div class="row">

                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Tên đăng nhập</label>
                                    <input type="text" class="form-control" placeholder="Tên đăng nhập"
                                           spellcheck="false" data-ms-editor="true">
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Mật khẩu</label>
                                    <input type="password" class="form-control" placeholder="Mật khẩu">
                                </div>
                            </div>
                            <div class="col-md-6 offset-md-3">
                                <button type="submit" class="btn default-btn">
                                    Đăng nhập
                                </button>
                            </div>
                            <div class="col-lg-12">
                                <p>
                                    Bạn chưa có tài khoản?
                                    <a href="@Url.Action("DangKy","TaiKhoan")">Đăng ký</a>
                                </p>
                            </div>
                            <div class="col-lg-12">
                                <ul class="social-list">
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-linkedin"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

BTL_ASP/CuaHangRuou/CuaHangRuou/CuaHangRuou/CuaHangRuou/Views/TaiKhoan/DoiMatKhau.cshtml
@{
    ViewBag.Title = "Đổi mật khẩu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- login -->
<section class="login-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6 col-md-6 p-0">
                <div class="log-in-bg"></div>
            </div>
            <div class="col-lg-6 col-md-6 p-0">
                <div class="login-form">
                    <h3>Đổi mật khẩu</h3>
                    <form>
                        <div class="row">

                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Mật khẩu cũ</label>
                                    <input type="password" class="form-control" placeholder="Mật khẩu cũ">
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Mật khẩu mới</label>
                                    <input type="password" class="form-control" placeholder="Mật khẩu mới">
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Nhập lại mật khẩu mới</label>
                                    <input type="password" class="form-control" placeholder="Nhập lại mật khẩu mới">
                                </div>
                            </div>
                            <div class="col-md-6 offset-md-3">
                                <button type="submit" class="btn default-btn">
                                    Đổi mật khẩu
                                </button>
                            </div>
                            <div class="col-lg-12">
                                <p>
                                    Bạn chưa đăng nhập?
                                    <a href="@Url.Action("DangNhap","TaiKhoan")">Đăng nhập</a>
                                </p>
                            </div>
                            <div class="col-lg-12">
                                <ul class="social-list">
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-linkedin"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>